server:
  port: 8088


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.235.211.11:3318/timo?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
  ## jpa配置
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate.dialect: com.linln.common.mysql.MySQLDialectUTF8
#      hibernate.format_sql: false
#    open-in-view: true

  ## thymeleaf模板设置
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false


### 基本的项目配置
project:
  captcha-open: false                         #是否开启登录验证码
  shiro:
    remember-me-timeout: 7                    #cookie记住登录信息时间，默认7天（天）
    global-session-timeout: 1800              #Session会话超时时间，默认30分钟（秒）
  upload:
    #file-path:                               #文件上传路径，默认在项目根目录upload下
    static-path: /upload/**                   #上传文件静态访问路径